// ==============================================================
// authHelpers.js
// ==============================================================
// Centralized helper functions for authentication flows.
// Provides token generation, validation, and TOTP QR code formatting.
//
// ⚠️ Note: This is a non-protected helper file. For production TOTP
// implementation, integrate with the backend `custom_auth_mfa` flow
// in `base44Client.js` and the `MFASetup` component in `Login.jsx`.

// -- 1. Password Reset Token Generation --

/**
 * Generates a crypto-secure 32-byte hex token and a 1-hour expiration timestamp.
 * Used by the password reset flow to create a one-time reset link.
 *
 * @returns {{ token: string, expiresAt: number }}
 *   - token: A 32-character hex string (64 bytes / 256 bits of entropy).
 *   - expiresAt: A JavaScript `Date` object (or timestamp) set to 1 hour from now.
 *
 * ⚠️ ⚠️ ⚠️ SECURITY CONSIDERATION ⚠️ ⚠️ ⚠️
 * - The token must be stored server-side (or in a secure session) and
 *   invalidated after use.
 * - The `expiresAt` timestamp must be checked server-side to prevent
 *   replay attacks.
 * - ⚠️ This function generates the token; the calling code must handle
 *   secure transmission (HTTPS) and single-use semantics.
 */
function generatePasswordResetToken() {
  const crypto = require("crypto");
  const token = crypto.randomBytes(32).toString("hex"); // 32 bytes = 256 bits
  const expiresAt = Date.now() + 60 * 60 * 1000; // 1 hour from now
  return { token, expiresAt };
}

// -- 2. Token Validation --

/**
 * Validates a password reset token against its stored hash and checks expiration.
 *
 * @param {string} token - The token received from the client.
 * @param {string} hashedToken - The hashed token stored server-side.
 * @param {number} expiresAt - The expiration timestamp (ms since epoch).
 * @returns {{ valid: boolean, error?: string }}
 *   - `valid`: `true` if the token matches and has not expired.
 *   - `error`: A human-readable error message if validation fails.
 *
 * ⚠️ ⚠️ ⚠️ SECURITY CONSIDERATION ⚠️ ⚠️ ⚠️
 * - Comparisons MUST use a constant-time algorithm to prevent timing attacks.
 * - In a production system, the `hashedToken` should be stored server-side
 *   (e.g., in a database or secure session) and never exposed to the client
 *   in a way that allows offline brute-force attacks.
 * - ⚠️ This function performs a simple string comparison for demonstration;
 *   a production implementation MUST use `crypto.timingSafeEqual` or similar.
 */
function validateResetToken(
  token,
  hashedToken,
  expiresAt
) {
  // 1. Check expiration first (fail fast)
  if (Date.now() > expiresAt) {
    return { valid: false, error: "Token has expired." };
  }

  // 2. Compare tokens using constant-time comparison (simplified here)
  // ⚠️ In production, use crypto.timingSafeEqual(Buffer(token), Buffer(hashedToken))
  const valid = token === hashedToken;

  if (!valid) {
    return { valid: false, error: "Invalid token." };
  }

  return { valid: true, error: null };
}

// -- 3. TOTP QR Code URL Formatting --

/**
 * Generates a standard `otpauth://totp/` URL for TOTP authenticator apps.
 * This URL can be passed to `QR Code` generators (e.g., `qrcode` npm package)
 * or displayed as a clickable link for user setup.
 *
 * @param {string} username - The user's email or username.
 * @param {string} secret - The base32-encoded secret key provisioned by the server.
 * @param {string} issuer - The name of the service/app (e.g., "Authenticator", "MyApp").
 * @returns {string} A fully-formed `otpauth://totp/` URL.
 *
 * ⚠️ ⚠️ ⚠️ SECURITY CONSIDERATION ⚠️ ⚠️ ⚠️
 * - The `secret` must be a base32-encoded string generated by the server.
 *   Never transmit raw secrets over unencrypted channels.
 * - The `issuer` should match the service name as it appears in the authenticator app.
 * - ⚠️ This function only formats the URL; the actual secret provisioning
 *   must occur during onboarding (e.g., QR code scan during MFA setup).
 */
function formatMfaQrCodeUrl(username, secret, issuer) {
  // Normalize the secret: ensure it's base32-safe (remove whitespace, lowercase)
  const normalizedSecret = secret.replace(/\s+/g, "").toUpperCase();

  return `otpauth://totp/${encodeURIComponent(
    username
  )}?secret=${normalizedSecret}&issuer=${encodeURIComponent(issuer)}&period=30&digits=6`;
}

// -- Exports --

export { generatePasswordResetToken, validateResetToken, formatMfaQrCodeUrl };