/**
 * Shared payroll calculation utilities
 * Used by Payroll page, autoPayroll engine, and historical posting
 */

/**
 * @typedef {Object} PayInput
 * @property {string} [pay_type] "salary" treats `base_rate` as the whole period
 *   amount; anything else multiplies it by `hours`.
 * @property {string|number} [base_rate]
 * @property {string|number} [hours]
 * @property {string|number} [overtime_hours]
 * @property {string|number} [overtime_rate] Defaults to 1.5x base_rate.
 * @property {string|number} [bonus]
 * @property {string|number} [deductions]
 */

/**
 * Every field is coerced with `Number(...) || 0`, so callers may pass raw
 * `<input>` strings without parsing them first, and may omit anything that has
 * a sensible zero/derived default.
 *
 * @param {PayInput} input
 */
export function calculatePay({
  pay_type,
  base_rate,
  hours = 0,
  overtime_hours = 0,
  overtime_rate,
  bonus = 0,
  deductions = 0,
}) {
  const br = Number(base_rate) || 0;
  const hrs = Number(hours) || 0;
  const otHrs = Number(overtime_hours) || 0;
  const otRate = Number(overtime_rate) || br * 1.5;
  const bns = Number(bonus) || 0;
  const ded = Number(deductions) || 0;

  const regularPay = pay_type === "salary" ? br : br * hrs;
  const overtimePay = otHrs * otRate;
  const totalPay = regularPay + overtimePay + bns - ded;

  return {
    base_rate: br,
    hours: hrs,
    overtime_hours: otHrs,
    overtime_rate: otRate,
    regular_pay: regularPay,
    overtime_pay: overtimePay,
    bonus: bns,
    deductions: ded,
    total_pay: totalPay,
  };
}

export function calculatePayFromStaff(staff) {
  return calculatePay({
    pay_type: staff.pay_type,
    base_rate: staff.base_rate,
    hours: staff.hours,
    overtime_hours: staff.overtime_hours,
    overtime_rate: staff.overtime_rate,
    bonus: staff.bonus,
    deductions: staff.deductions,
  });
}

export function buildPayrollRunRecord({
  staff,
  payCalc,
  periodStart,
  periodEnd,
  status = "paid",
  propertyId = "",
  propertyName = "",
  autoGenerated = false,
  employeeId = null,
}) {
  const now = new Date().toISOString();
  return {
    employee_name: staff.employee_name,
    department: staff.department || "",
    pay_type: staff.pay_type || "hourly",
    ...payCalc,
    payroll_status: status,
    pay_period_start: periodStart,
    pay_period_end: periodEnd,
    property_id: propertyId,
    property_name: propertyName,
    auto_generated: autoGenerated,
    employee_id: employeeId || staff.employee_id || "",
    created_date: now,
    updated_date: now,
  };
}

export function generateMonthPeriods(fromYear, fromMonth, toYear, toMonth) {
  const periods = [];
  let y = fromYear, m = fromMonth;
  while (y < toYear || (y === toYear && m <= toMonth)) {
    const days = lastDayOf(y, m);
    periods.push({
      year: y,
      month: m,
      label: monthLabel(y, m),
      periodStart: iso(y, m, 1),
      periodEnd: iso(y, m, days),
      days,
    });
    if (m === 11) { m = 0; y++; } else { m++; }
  }
  return periods;
}

const MONTHS = ["January","February","March","April","May","June","July","August","September","October","November","December"];
const pad = (n) => String(n).padStart(2, "0");
const iso = (y, m, d) => `${y}-${pad(m + 1)}-${pad(d)}`;
const lastDayOf = (y, m) => new Date(y, m + 1, 0).getDate();
const monthLabel = (y, m) => `${MONTHS[m]} ${y}`;

/**
 * Normalise a (year, month) pair that may have over/underflowed — e.g. the
 * "previous month" default is `getMonth() - 1`, which is -1 every January.
 * Returns a pair with month back inside 0..11 and the year carried.
 */
export function normalizeMonth(year, month) {
  const y = Number(year);
  const m = Number(month);
  if (!Number.isFinite(y) || !Number.isFinite(m)) {
    const now = new Date();
    return { year: now.getFullYear(), month: now.getMonth() };
  }
  return { year: y + Math.floor(m / 12), month: ((m % 12) + 12) % 12 };
}

/** Full calendar month as a payroll period. */
export function monthPeriod(year, month) {
  const { year: y, month: m } = normalizeMonth(year, month);
  const days = lastDayOf(y, m);
  return {
    year: y,
    month: m,
    label: monthLabel(y, m),
    periodStart: iso(y, m, 1),
    periodEnd: iso(y, m, days),
    days,
  };
}

/** The calendar month before `date` (defaults to today). */
export function previousMonth(date = new Date()) {
  return normalizeMonth(date.getFullYear(), date.getMonth() - 1);
}

/**
 * The engine's cron is `0 9 28-31 * *` and it no-ops unless the day is the last
 * of the month, so the next run is always the final day of the current month —
 * or of the next month once today's run has already passed.
 */
export function nextPayrollDate(from = new Date()) {
  const y = from.getFullYear();
  const m = from.getMonth();
  if (from.getDate() < lastDayOf(y, m)) return iso(y, m, lastDayOf(y, m));
  const { year: ny, month: nm } = normalizeMonth(y, m + 1);
  return iso(ny, nm, lastDayOf(ny, nm));
}

/**
 * Payroll statuses that represent committed money.
 *
 * A `draft` run is a work-in-progress figure, so it must NOT move the owner's
 * "money kept" or any profit number — otherwise a half-typed entry silently
 * changes the dashboard. `approved` and `paid` are both commitments: approved
 * means the amount is agreed and owed, paid means it has left the account.
 *
 * Every consumer that deducts payroll from revenue MUST filter through
 * `filterCommittedPay`/`sumCommittedPay` so the dashboard, Action Center,
 * Expenses and Forecasting can never disagree about the same month.
 */
export const COMMITTED_PAYROLL_STATUSES = ["approved", "paid"];

export function isCommittedPayroll(run) {
  return COMMITTED_PAYROLL_STATUSES.includes(run?.payroll_status || "draft");
}

export function filterCommittedPay(runs = []) {
  return runs.filter(isCommittedPayroll);
}

export function sumCommittedPay(runs = []) {
  return filterCommittedPay(runs).reduce((a, r) => a + (Number(r.total_pay) || 0), 0);
}

export { MONTHS, pad, iso, lastDayOf, monthLabel };