// @ts-nocheck
import "fake-indexeddb/auto";
import { beforeEach, describe, expect, it } from "vitest";

// Pin Node WebCrypto like the other harness scripts (jsdom may lack subtle).
globalThis.crypto ??= await import("node:crypto").then((m) => m.webcrypto);
if (!globalThis.crypto?.subtle) globalThis.crypto = await import("node:crypto").then((m) => m.webcrypto);

const __store = new Map();
const __storage = {
  getItem: (k) => (__store.has(k) ? __store.get(k) : null),
  setItem: (k, v) => __store.set(k, String(v)),
  removeItem: (k) => __store.delete(k),
  clear: () => __store.clear(),
};
globalThis.localStorage = __storage;
globalThis.sessionStorage = __storage;
globalThis.window = globalThis;

const { secureStore, secureRetrieve, createAuditEntry, verifyAuditChain } = await import("@/lib/securityUtils");
const localDbModule = await import("@/api/localDb");
const localDb = localDbModule.default;

// ─── Helpers ───

// `securityUtils.js` is a PROTECTED file, so we exercise the audit chain via
// its public surface (createAuditEntry + verifyAuditChain) rather than by
// importing the private hashEntry() or by stubbing crypto. createAuditEntry
// stamps each row with `new Date().toISOString()`, and reads the previous
// hash from localDb.AuditLog.orderBy('created_date').reverse().first() — so we
// sleep 2ms between inserts to guarantee strictly increasing created_date and
// deterministic chain ordering. Hash determinism comes from createAuditEntry
// hashing the same field set that verifyAuditChain recomputes over.
const tick = () => new Promise((r) => setTimeout(r, 3));

// Build N audit rows whose local chain is internally consistent. Each row is
// generated by createAuditEntry (which fetches the previous hash from localDb)
// then persisted into localDb.AuditLog using the snake_case column names
// verifyAuditChain reads back. Returns the inserted rows in insertion order.
async function seedChain(rows) {
  const inserted = [];
  for (let i = 0; i < rows.length; i++) {
    if (i > 0) await tick();
    const r = rows[i];
    const entry = await createAuditEntry(r.action, {
      userId: r.user_id ?? null,
      username: r.username ?? "unknown",
      performedById: r.performed_by_id ?? null,
      performedBy: r.performed_by ?? "system",
      propertyId: r.property_id ?? null,
      propertyName: r.property_name ?? null,
      result: r.result ?? "success",
      detail: r.detail ?? "",
    });
    const id = await localDb.AuditLog.add({
      action: entry.action,
      created_date: entry.timestamp,
      ip_address: entry.ipAddress,
      device: entry.device,
      user_id: entry.userId,
      username: entry.username,
      performed_by_id: entry.performedById,
      performed_by: entry.performedBy,
      property_id: entry.propertyId,
      property_name: entry.propertyName,
      result: entry.result,
      detail: entry.detail,
      hash: entry.hash,
      previous_hash: entry.previous_hash,
    });
    inserted.push({ ...entry, id, created_date: entry.timestamp });
  }
  return inserted;
}

beforeEach(async () => {
  __store.clear();
  try {
    await localDb.AuditLog.clear();
  } catch {}
});

describe("secureStore / secureRetrieve", () => {
  it("round-trips when IndexedDB is available", async () => {
    const ok = await secureStore("probe_idb", { value: 42 });
    expect(ok).toBe(true);
    const got = await secureRetrieve("probe_idb");
    expect(got).toEqual({ value: 42 });
  });

  it("round-trips even when IndexedDB is unavailable (fallback key)", async () => {
    // Simulate private-browsing / IndexedDB disabled: openCryptoDB must reject.
    const realIDB = globalThis.indexedDB;
    delete globalThis.indexedDB;
    try {
      const ok = await secureStore("probe_fallback", { value: 7 });
      expect(ok).toBe(true);
      const got = await secureRetrieve("probe_fallback");
      expect(got).toEqual({ value: 7 });
    } finally {
      globalThis.indexedDB = realIDB;
    }
  });
});

describe("audit chain — createAuditEntry / verifyAuditChain", () => {
  it("verifies an empty chain", async () => {
    const res = await verifyAuditChain();
    expect(res.valid).toBe(true);
    expect(res.count).toBe(0);
  });

  it("verifies a healthy 3-entry chain end-to-end", async () => {
    await seedChain([
      { action: "User Login",         username: "alice", performed_by: "alice", result: "success", detail: "ok" },
      { action: "Password Changed",    username: "alice", performed_by: "alice", result: "success", detail: "rotated" },
      { action: "User Created",       username: "bob",   performed_by: "alice", result: "success", detail: "added bob" },
    ]);
    const res = await verifyAuditChain();
    expect(res.valid).toBe(true);
    expect(res.count).toBe(3);
  });

  it("deterministically detects content tampering (mimics a DB-admin edit)", async () => {
    const inserted = await seedChain([
      { action: "User Login",       username: "alice", performed_by: "alice", result: "success", detail: "ok" },
      { action: "Void Adjustment",  username: "alice", performed_by: "alice", result: "success", detail: "$200 void" },
    ]);
    // Simulate an admin editing the second row's detail in the DB to hide fraud.
    await localDb.AuditLog.update(inserted[1].id, { detail: "$2 void (harmless)" });

    const res = await verifyAuditChain();
    expect(res.valid).toBe(false);
    expect(res.tamperedAt).toBe(inserted[1].id);
    expect(typeof res.expected).toBe("string");
    expect(typeof res.actual).toBe("string");
    expect(res.expected).not.toBe(res.actual);
    expect(res.expected.length).toBe(64); // HMAC-SHA-256 hex
  });

  it("detects when a row has been deleted from the middle of the chain (DB-admin truncation)", async () => {
    const inserted = await seedChain([
      { action: "User Login",        username: "alice", performed_by: "alice", result: "success", detail: "ok" },
      { action: "Suspicious Action",  username: "alice", performed_by: "alice", result: "success", detail: "$200 void" },
      { action: "User Logout",       username: "alice", performed_by: "alice", result: "success", detail: "ok" },
    ]);
    // Attacker with DB admin access deletes the suspicious middle row to hide
    // it. Row[2]'s OWN stored hash still validates against its own content
    // (the canonical is unchanged), so the hash-mismatch check passes for it.
    // But the chain-link continuity check fires: row[2]'s stored previous_hash
    // is row[1]'s hash (which no longer exists), while the verifier's running
    // previousHash is row[0]'s hash. This is the realistic way to reach the
    // documented "Chain break" branch — deletion can't recompute the secret,
    // so the chain link breaks rather than the row's own hash.
    await localDb.AuditLog.delete(inserted[1].id);

    const res = await verifyAuditChain();
    expect(res.valid).toBe(false);
    expect(res.tamperedAt).toBe(inserted[2].id);
    expect(res.reason).toMatch(/chain break/i);
    expect(res.expectedPrevious).toBe(inserted[0].hash);
    expect(res.actualPrevious).toBe(inserted[1].hash);
  });
});
