import os

prompts = """
## 5. ADVANCED LEVEL-100 PROMPTS (ADDITIONAL 30 PROMPTS)

### 1. Dynamic Revenue Strategy & Displacement Analysis
- **Group vs. Transient Displacement Calculation:** "When a group block (BLK) requests 15 rooms for 3 nights in July at a contracted rate of $89/night, calculate the revenue displacement cost if our forecasted unconstrained transient ADR is $189.55 at 85% occupancy. Should ownership accept or reject the group block?"
- **Unconstrained Demand & Rate Floor Strategy:** "Based on July’s 84.5% occupancy and $189.55 ADR, determine our price elasticity threshold: how much can we increase weekend ADR before occupancy drops below the revenue-maximizing point?"
- **Length-of-Stay (LOS) Yield Optimization:** "Identify all 1-night stays on peak Fridays and Saturdays in July. Calculate the net revenue gain if we enforced a 2-night minimum length-of-stay (MinLOS) restriction on high-demand weekends."
- **Cancellation & No-Show Revenue Retention:** "Analyze total cancellations and no-shows from All Transactions.csv across Booking.com, Expedia, and Direct channels. What percentage of late-cancellation penalty charges were successfully collected versus written off or refunded?"
- **Day-of-Week ADR Spread Analysis:** "What is the net ADR spread between mid-week business stays (Tue–Thu) and weekend leisure stays (Fri–Sat)? Which specific channels drive our mid-week baseline versus weekend peaks?"

### 2. Cost Per Occupied Room (CPOR) & Labor Efficiency
- **Variable CPOR Breakdown:** "Divide total operating expenses for July by total rooms sold (2,619 stays) to calculate our Cost Per Occupied Room (CPOR). Break this down into variable cleaning supplies, laundry, utilities, and credit card processing fees per occupied key."
- **Housekeeping Labor Efficiency Metric:** "Calculate total housekeeping payroll against total rooms cleaned in July. What is our labor cost per cleaned room, and how does it compare to our off-peak baseline in January?"
- **Overtime & Staffing Sensitivity:** "Analyze payroll runs from PayrollRun tables: how many overtime hours were logged during peak July weeks, and what was the net margin drag of overtime vs. hiring an additional part-time clerk?"
- **Utility Utility-to-Occupancy Correlation:** "Correlate monthly utility expenses (electricity, water, gas) against total sold room nights from January through July. What is our fixed utility base cost vs. the marginal utility cost per room night?"
- **Maintenance & Out-of-Order (OOO) Revenue Loss:** "Calculate the total RevPAR loss caused by Down/OOO rooms during peak July dates. If 3 rooms were down for 10 days at an average ADR of $189.55, what was the exact top-line revenue impact?"

### 3. Channel Distribution, Merchant Fees & Net Margin Optimization
- **Net ADR Matrix Across All Channels:** "Generate a Net ADR Matrix for all 12 active distribution sources in July by subtracting channel-specific commissions (e.g., Expedia 15%, Agoda 15%), card processing fees (2.5%), and merchant fees from gross revenue. Rank channels strictly by net cash retained per room night."
- **Merchant Model vs. Hotel Collect Yield Comparison:** "Compare net cash flow timing and net revenue between Expedia Hotel Collect (EHC - $131.71 ADR) and Expedia Collect (EXP - $103.51 ADR). Accounting for credit card processing and commission billing, which model yields higher net margin to the property?"
- **Direct Booking Conversion Investment Return:** "If we spend $1,500/month on local Google Ads and SEO to shift 50 room nights from Booking.com ($133.32 ADR, 15% commission) to the brand website (WEB - $124.88 ADR, 0% commission), what is the net monthly ROI of that marketing spend?"
- **Corporate & Direct Bill (LDB) Credit Risk:** "Analyze all Direct Bill (LDB) transactions in the ledger: what is the total aging balance past 30 days, and what is our net write-off risk relative to total monthly revenue?"
- **Loyalty Certificate & Discount Drag:** "Calculate the total revenue loss from RediCard/loyalty redemptions and promotional discounts in July. What was the net ADR impact of loyalty stays compared to standard rack-rate stays?"

### 4. Forensic Ledger Auditing & Anomaly Detection
- **Closed Folio Refund & Adjustment Audit:** "Scan transactionNorm.js rules: search the ledger for any transaction where a refund or negative adjustment was posted to a folio AFTER guest check-out. Flag all instances, total amounts, and associated usernames."
- **Transferred Transactions Audit:** "Identify all ledger entries flagged with transferred_transactions. Trace charges moved between guest folios, house accounts, and master folios to verify no charges were erased or misallocated."
- **Account Classification Fraud Check:** "Filter ledger activity by user account type (Staff, System, Agency, Brand per transactionNorm.js). Are any system integration accounts (e.g., hkcrsuser) posting manual rate overrides, cash adjustments, or refunds?"
- **Zero-Rate & House Room Audit:** "List all room nights logged as Zero Rate or House Use in July. Cross-reference these room numbers with front-desk shift logs to confirm proper authorization and prevent unrecorded cash walk-in fraud."
- **POS Check & Miscellaneous Charge Reconciliation:** "Reconcile total POS check charges against miscellaneous revenue categories (vending, laundry, pet fees, early check-in). Are all POS charges supported by itemized ledger line entries?"

### 5. Asset Management, NOI & Real Estate Ownership KPIs
- **Gross Operating Profit Per Available Room (GOPPAR):** "Calculate GOPPAR for July 2026: (Total Revenue − Total Operating Expenses − Total Payroll) ÷ Total Available Rooms (3,100 room-nights). How does this compare to January’s GOPPAR?"
- **Net Operating Income (NOI) Expansion:** "Project full-year NOI based on current YTD trend data in acceptance-report.json. What is the projected asset valuation assuming an 8.5% capitalization rate?"
- **Debt Service Coverage Ratio (DSCR) Headroom:** "Assuming an annual debt service obligation of $180,000 ($15,000/month), calculate our DSCR for January (low season) vs. July (peak season). Does January net cash flow safely cover debt service without drawing on reserves?"
- **CapEx Reserve Allocation Modeling:** "Calculate a 4% Furniture, Fixtures & Equipment (FF&E) CapEx reserve deduction from July gross revenue ($231,075.29). What is the net cash available for owner distribution after debt service and FF&E reserve?"
- **Seasonal Cash Reserve Buffer Calculation:** "Based on January’s total deductions ($48,648.45) versus net profit, how much cash buffer must be set aside from summer profits (June–August) to fully fund winter operational deficits without external capital injections?"

### 6. AI Engine Technical & Logic Prompts
- **Integer Cents Precision Audit:** "Verify that all financial aggregations in aiEngine.js utilize integer cents arithmetic (toCents, sumCents) to eliminate floating-point rounding errors across multi-thousand row datasets."
- **Taxable Base vs. Gross Tax Discrepancy:** "Compare estimated state tax (11.7%) against actual imported tax lines from PMS reports. Identify any exempt revenue sources that were incorrectly included in the taxable base calculation."
- **Multi-Property Role-Based Access Isolation:** "Verify that queries executed by users assigned to 'Manager' or 'Front Desk' roles strictly filter records by property_access boundaries and prevent cross-property data leaks in multi-property portfolio views."
- **Audit Trail Hash Chain Integrity:** "Check the HMAC-SHA256 audit log hash chain in AuditLog table records. Are there any broken previous-hash links or tampered entries in user activity logs?"
- **Rolling 30-Day Cash Flow Projection Engine:** "Combine historical 30-day occupancy trends, recurring expense projections, and scheduled bi-weekly payroll to generate a forward-looking 30-day net cash flow forecast for Middleborough."

## 6. PRODUCTION-READY SYSTEM PROMPTS & TRAINING INPUTS (50 PROMPTS)

### Category 1: Executive P&L, Flow-Through & Net Profit ("Money Kept")
- **Prompt 1**: *System Instruction*: You are an executive hotel analytics AI specializing in P&L analysis. Always calculate net profit using: `Net Revenue − (Payroll + Operating Expenses + OTA Commissions + Credit Card Processing Fees + Estimated Taxes)`. Ensure money is calculated using integer cents arithmetic. *User Input*: "Analyze our overall financial performance for Middleborough in January 2026. What was our gross revenue, total deductions, and final 'Money Kept' (Net Profit)? Explain why net profit was low relative to revenue."
- **Prompt 2**: *System Instruction*: Evaluate operating leverage and net flow-through. Flow-through measures what percentage of incremental revenue converts to net operating income. *User Input*: "Compare January 2026 ($57,134.22 revenue) to July 2026 ($231,075.29 revenue). What was our net flow-through percentage, and how much did fixed-cost compression contribute to July's profit expansion?"
- **Prompt 3**: *System Instruction*: You are a hotel asset manager. Calculate break-even occupancy based on fixed operational costs versus variable cost per occupied room (CPOR). *User Input*: "Our fixed monthly costs for Middleborough (base payroll, utilities, insurance, software) total $11,500. Variable CPOR is $18.50. At an off-peak ADR of $72.78, how many room nights and what occupancy percentage do we need just to break even?"
- **Prompt 4**: *System Instruction*: Analyze seasonality risks and determine winter cash reserve requirements. *User Input*: "Based on our January operating deductions ($48,648.45), how much cash reserve must be set aside from peak summer cash flows (June–August) to cover low-occupancy winter operating deficits?"
- **Prompt 5**: *System Instruction*: Evaluate Gross Operating Profit Per Available Room (GOPPAR) across properties. *User Input*: "Calculate GOPPAR for July 2026 across 100 available rooms (3,100 total room nights). How does GOPPAR compare between Middleborough and Phoenix West?"

### Category 2: Revenue Management, RevPAR & Yield Optimization
- **Prompt 6**: *System Instruction*: You are a revenue manager. Always evaluate ADR, Occupancy, and RevPAR together. `RevPAR = Total Revenue / Total Available Rooms` or `ADR × Occupancy Rate`. *User Input*: "In July 2026, Middleborough achieved an ADR of $189.55 at 84.5% occupancy. If we had raised rates to $209.00 and occupancy dropped to 76.0%, would total room revenue have increased or decreased? Show the exact dollar difference."
- **Prompt 7**: *System Instruction*: Analyze rate elasticity and displacement for group bookings versus transient demand. *User Input*: "A construction crew wants to book 20 rooms for 5 nights in July at a discounted group rate of $95.00/night. Unconstrained transient demand projects 85% occupancy at $189.55 ADR. Calculate the displacement cost and advise whether to accept the group."
- **Prompt 8**: *System Instruction*: Evaluate length-of-stay (LOS) restrictions on peak weekend dates. *User Input*: "Review July weekend arrivals. If 35% of Friday bookings were 1-night stays that left Saturday unbooked, what is the net revenue impact of enforcing a 2-night Minimum Length of Stay (MinLOS) on peak summer weekends?"
- **Prompt 9**: *System Instruction*: Identify revenue loss from Out-of-Order (OOO) and Down rooms. *User Input*: "During July, an average of 4 rooms per day were listed as Out of Order due to maintenance. At our July RevPAR of $74.54, what was the total uncaptured revenue loss for the month?"
- **Prompt 10**: *System Instruction*: Analyze day-of-week performance trends. *User Input*: "Break down RevPAR and ADR for July 2026 by day of the week (Sunday through Saturday). Which days represent our highest yield, and where is our biggest rate leakage?"

### Category 3: Channel Distribution & OTA Net Commission Analysis
- **Prompt 11**: *System Instruction*: You are an OTA distribution analyst. Net channel ADR must subtract OTA commission (typically 15%) and credit card processing fees (2.5%) from gross ADR. *User Input*: "In July 2026, Booking.com (BHC) produced $25,063.50 across 188 stays ($133.32 gross ADR). Calculate the net retained ADR after deducting 15% commission and 2.5% card fees. Is this more profitable than a Walk-In guest at $97.11 ADR?"
- **Prompt 12**: *System Instruction*: Compare channel mix and net profit margins across all distribution partners. *User Input*: "Rank all active distribution channels in July 2026 (Expedia, Booking.com, Agoda, Walk-In, Direct Web, CRS) by total net revenue contribution after deducting commissions and fees."
- **Prompt 13**: *System Instruction*: Evaluate the financial return of shifting bookings from high-cost OTAs to direct channels. *User Input*: "If we spend $1,200/month on search marketing to shift 40 monthly stays from Expedia ($103.51 ADR, 15% commission) to Red Roof Direct Web ($124.88 ADR, 0% commission), what is our net monthly dollar return on investment (ROI)?"
- **Prompt 14**: *System Instruction*: Distinguish between Merchant Model (Expedia Collect) and Hotel Collect (BHC/EHC) cash flow dynamics. *User Input*: "Explain the net margin and cash collection differences between Expedia Collect (EXP) and Expedia Hotel Collect (EHC) based on our July data. Which model carries higher credit card processing fees for the property?"
- **Prompt 15**: *System Instruction*: Analyze corporate direct bill (LDB) credit risks and payment terms. *User Input*: "Review Direct Bill (LDB) revenue for Q2 2026. What is the total volume outstanding, and what is the working capital cost of carrying 60-day receivables vs. instant credit card settlement?"

### Category 4: Forensic Ledger Auditing & Anomaly Detection
- **Prompt 16**: *System Instruction*: You are a forensic hotel auditor. Per `transactionNorm.js`, charges increase folio balance (revenue), while refunds/payments decrease folio balance. *User Input*: "Scan the July ledger for any transaction where a refund or negative rate adjustment was posted after guest check-out. Identify suspicious folio numbers, usernames, and amounts."
- **Prompt 17**: *System Instruction*: Audit front-desk clerk cash drops against expected cash payments. *User Input*: "Review the Clerk Shift Audit report for January 2026. Identify the top 3 clerks with the largest cash drop shortages, total shortage amounts, and their variance relative to total shift drops."
- **Prompt 18**: *System Instruction*: Detect unrecorded cash walk-in fraud by auditing zero-rate and house rooms. *User Input*: "Cross-reference all rooms logged as 'Zero Rate', 'House Use', or 'Comp' in July against front-desk clerk shift logs. Are there any room nights assigned a $0 rate without a logged management remark?"
- **Prompt 19**: *System Instruction*: Analyze user account classification in transaction logs. *User Input*: "Filter transaction logs by account classification (Staff, System, Agency, Brand). Did any system accounts (e.g., `hkcrsuser`) execute manual rate overrides or folio adjustments during July?"
- **Prompt 20**: *System Instruction*: Audit transferred transactions and folio balance movements. *User Input*: "Search `TransactionLine` for all entries flagged as `transferred_transactions`. Identify any balances moved between guest folios and house accounts that resulted in unpaid net balances."

### Category 5: Operational Expenses, Payroll & Labor Efficiency
- **Prompt 21**: *System Instruction*: Analyze labor cost percentage and housekeeping efficiency. *User Input*: "In January 2026, payroll was $6,800 on $57,134 revenue (11.9% labor ratio). In July, payroll was $12,500 on $231,075 revenue (5.4% labor ratio). Calculate our labor cost per occupied room (CPOR) for both months."
- **Prompt 22**: *System Instruction*: Audit overtime spending and payroll variance. *User Input*: "Review biweekly payroll runs in `PayrollRun` for Q2 2026. Identify total overtime hours worked by department (Front Desk vs. Housekeeping) and calculate the net savings if 20 overtime hours were replaced by part-time shifts at base rate."
- **Prompt 23**: *System Instruction*: Analyze operating expense categorization and utility seasonality. *User Input*: "Categorize all non-payroll operating expenses for July 2026 (Utilities, Guest Supplies, Maintenance, Franchise Fees). What percentage of total operating costs did utility expenses represent?"
- **Prompt 24**: *System Instruction*: Evaluate recurring expense projections and vendor payables. *User Input*: "Identify all recurring monthly operating expenses due in the next 14 days. What is the total cash outflow required to satisfy vendor payables?"
- **Prompt 25**: *System Instruction*: Reconcile credit card merchant fees against total card volume. *User Input*: "In January 2026, card processing volume was $47,455.13. At a configured rate of 2.5%, processing fees were $1,186.38. If merchant processor rates increase to 2.85%, what is the annual net profit impact across $1,000,000 in card volume?"

### Category 6: Tax Compliance, Audit Trails & System Integrity
- **Prompt 26**: *System Instruction*: You are a hotel tax compliance auditor. Calculate state and local occupancy taxes based on taxable room revenue date windows. *User Input*: "Calculate estimated state occupancy tax (11.70%) on January 2026 net taxable room revenue ($57,134.22). Explain why exempt room revenue must be excluded prior to applying tax rates."
- **Prompt 27**: *System Instruction*: Verify system database integrity and schema relationships. *User Input*: "Run a database referential integrity check across `OccupancyDay`, `SourceDay`, `Expense`, and `PayrollRun` tables. Are there any orphan records referencing non-existent property IDs?"
- **Prompt 28**: *System Instruction*: Validate audit log hash chain tamper detection. *User Input*: "Verify the HMAC-SHA256 hash chaining mechanism in `AuditLog`. How does the system detect if a user modifies or deletes a historical audit log record?"
- **Prompt 29**: *System Instruction*: Test property-level data isolation for multi-property role-based access. *User Input*: "A user assigned to 'Manager' role with access only to Property #1 requests a portfolio revenue summary. Verify that the query engine strictly restricts results to Property #1 and excludes Property #2 data."
- **Prompt 30**: *System Instruction*: Audit CSV report auto-detection and deduplication mechanics. *User Input*: "When a user uploads `Source Summary (3).csv` twice, how does the system parser use composite business keys (`dedupByKey`) and `import_id` tracking to prevent duplicate revenue ingestion?"

### Category 7: Asset Valuation, NOI & Real Estate Investment
- **Prompt 31**: *System Instruction*: You are a commercial real estate analyst. Calculate Net Operating Income (NOI) and estimated hotel property valuation using capitalization rates. *User Input*: "Assuming Middleborough generates $450,000 in annual Net Operating Income (NOI), calculate the estimated asset valuation at an 8.0%, 8.5%, and 9.0% Cap Rate."
- **Prompt 32**: *System Instruction*: Model Debt Service Coverage Ratio (DSCR) under varying demand scenarios. *User Input*: "Our annual debt service (principal + interest) is $140,000 ($11,666/month). Calculate our DSCR for January 2026 ($8,485 net cash flow) versus July 2026 (~$218,000 net cash flow). Is the property in default during winter months?"
- **Prompt 33**: *System Instruction*: Model CapEx reserves (FF&E) for property renovation. *User Input*: "Calculate a 4.0% FF&E CapEx reserve deduction from July gross revenue ($231,075.29). What is the remaining net cash available for owner distribution after debt service ($11,666) and CapEx reserve?"
- **Prompt 34**: *System Instruction*: Evaluate year-over-year asset appreciation and RevPAR Index. *User Input*: "Middleborough's RevPAR increased from $18.43 in January to $74.54 in July. If competitive market RevPAR grew by 15% over the same period, did our property gain or lose market share?"
- **Prompt 35**: *System Instruction*: Model capital allocation for room renovation vs. digital marketing. *User Input*: "We have $50,000 in capital. Option A: Renovate 10 bathrooms to increase overall ADR by $8.00 across 2,500 annual room nights. Option B: Invest in direct web marketing to shift 300 annual room nights from 15% OTA commission to 0% direct. Calculate the annual net dollar return for both options."

### Category 8: Advanced Scenarios & Multi-Variable Edge Cases
- **Prompt 36**: *System Instruction*: Evaluate double-counting risks when parsing stacked multi-section PMS exports. *User Input*: "In HotelKey `All Transactions.csv` exports, Section 1 (19 columns) and Section 5 (34 columns) contain identical transaction rows. Explain why ingesting both sections double-counts revenue by 31.1% and how the parser selects Section 5 safely."
- **Prompt 37**: *System Instruction*: Evaluate the impact of UTC date shift bugs on monthly revenue totals. *User Input*: "Why does parsing a date string like `2026-02-01` using standard `new Date()` cause revenue on the 1st of the month to be incorrectly credited to January in US timezones, and how does `filterByMonths` prevent this?"
- **Prompt 38**: *System Instruction*: Model dynamic pricing rules for local demand events. *User Input*: "A major concert in Boston increases regional lodging demand for a weekend in August. Historical occupancy for that weekend is 98%. What dynamic pricing strategy should we implement for 60-day out vs 7-day out bookings?"
- **Prompt 39**: *System Instruction*: Analyze refund mechanics and loyalty program discount impact. *User Input*: "Explain how closed folio refunds and loyalty certificate discounts are tracked in `PaymentDay` tables, and why they must be subtracted from gross charges to compute true Net Revenue."
- **Prompt 40**: *System Instruction*: Evaluate front-desk shift handoff cash reconciliation. *User Input*: "Shift 1 clerk drops $450 cash with expected cash payments of $500 ($50 short). Shift 2 clerk drops $600 cash with expected cash payments of $550 ($50 over). What is the total property variance, and how should management handle individual shift accountability?"

### Category 9: Strategic Portfolio & Multi-Property Benchmarking
- **Prompt 41**: *System Instruction*: Benchmark performance metrics across a multi-hotel portfolio. *User Input*: "Compare Middleborough (100 rooms) and Phoenix West (80 rooms) for July 2026 across Occupancy, ADR, RevPAR, Operating Cost per Room, and Net Margin %."
- **Prompt 42**: *System Instruction*: Analyze centralized vs. property-specific expense allocations. *User Input*: "Shared corporate software costs total $3,000/month. Allocate this expense between Middleborough (100 rooms) and Phoenix West (80 rooms) based on room count proportion, and calculate the net profit impact on each property."
- **Prompt 43**: *System Instruction*: Evaluate channel performance variance across portfolio properties. *User Input*: "Why does Booking.com generate 25% of total revenue at Middleborough but only 10% at Phoenix West? What local demographic or pricing factors explain this channel variance?"
- **Prompt 44**: *System Instruction*: Model portfolio-wide labor sharing efficiency. *User Input*: "If a regional maintenance supervisor splits time between Middleborough (60%) and Phoenix West (40%), how should their $5,000 monthly salary be recorded in `PayrollRun` for accurate property-level P&L reporting?"
- **Prompt 45**: *System Instruction*: Portfolio consolidation and cash flow aggregation. *User Input*: "Generate a consolidated Portfolio P&L for July 2026 combining Middleborough and Phoenix West. What was total portfolio gross revenue, total deductions, and net cash available for distribution?"

### Category 10: Predictive Forecasting & Actionable Insights
- **Prompt 46**: *System Instruction*: Forecast 30-day forward revenue using recent daily run rates. *User Input*: "Based on the last 14 days of July occupancy (85% avg) and ADR ($189.55), project total room revenue for the first 30 days of August."
- **Prompt 47**: *System Instruction*: Generate automated low-occupancy alerts and proactive pricing recommendations. *User Input*: "Scan the 14-day forward booking horizon. If occupancy for next Tuesday falls below 45%, what specific rate adjustment and channel promotion should the system recommend?"
- **Prompt 48**: *System Instruction*: Predict monthly payroll expense based on forecasted room nights. *User Input*: "Forecasted occupancy for August is 80% (2,480 sold rooms). At a baseline of 0.5 housekeeping hours per sold room at $16.00/hour plus 480 front-desk shift hours, what is our projected August payroll expense?"
- **Prompt 49**: *System Instruction*: Model inflation impact on operating expenses and required ADR growth. *User Input*: "If operating expenses (utilities, laundry, supplies) increase by 6% next year, how much must we increase our baseline ADR ($81.80 average) to maintain our current net profit margin?"
- **Prompt 50**: *System Instruction*: You are an AI executive assistant. Provide a concise, 4-bullet executive summary for hotel ownership. *User Input*: "Summarize July 2026 performance for Middleborough in 4 high-impact bullet points for ownership: Revenue, ADR/Occupancy, Net Profit, and Key Action Item for next month."
"""

with open('BUSINESS.md', 'a', encoding='utf-8') as f:
    f.write("\n" + prompts + "\n")
