import React from 'react';
import { Link } from 'react-router-dom';
import { FileText, ArrowLeft, Shield } from 'lucide-react';

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-800 py-10 px-4 sm:px-6 lg:px-8">
      <div className="max-w-3xl mx-auto bg-white rounded-2xl shadow-sm border border-gray-200 p-8 sm:p-12">
        <Link
          to="/login"
          className="inline-flex items-center gap-1.5 text-xs font-semibold text-red-700 hover:text-red-800 mb-6 transition"
        >
          <ArrowLeft className="h-4 w-4" /> Back to Application
        </Link>

        <div className="flex items-center gap-3 mb-6 pb-4 border-b border-gray-100">
          <div className="rounded-full bg-red-100 p-2.5 text-red-700">
            <FileText className="h-6 w-6" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-gray-900">Terms of Service</h1>
            <p className="text-xs text-gray-500">Effective Date: August 14, 2026</p>
          </div>
        </div>

        <div className="space-y-6 text-sm leading-relaxed text-gray-600">
          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>
              By accessing or using Red Roof Intelligence ("the Application"), you agree to be bound by these Terms of Service. If you do not agree to these terms, you may not access or use the Application.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">2. Authorized Use &amp; Account Responsibility</h2>
            <p>
              Access to the Application is restricted to authorized hotel personnel, managers, accountants, and property owners. Authorized users agree to:
            </p>
            <ul className="list-disc pl-5 space-y-1.5 mt-2">
              <li>Maintain the confidentiality of login credentials and multi-factor authentication (MFA) devices.</li>
              <li>Promptly report any suspected unauthorized access or compromised credentials.</li>
              <li>Use the Application solely for legitimate hotel business operations, financial reconciliation, and revenue management.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">3. Role Permissions &amp; System Integrity</h2>
            <p>
              Users must operate within their assigned permission tiers (e.g., Front Desk, Manager, Accountant, Admin, Owner). Attempting to bypass role restrictions, tamper with client-side state, forge audit entries, or inject malicious payloads via file uploads will result in immediate account termination and administrative audit flagging.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">4. Financial &amp; Yield Decision Disclaimer</h2>
            <p>
              Revenue recommendations, pricing suggestions, labor allocations, and anomaly flags generated by the Application are decision-support tools. Final pricing decisions, payroll distributions, and employee disciplinary actions remain the sole responsibility of hotel management and property owners.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">5. Service Availability &amp; Modifications</h2>
            <p>
              We strive to maintain continuous system availability, but we do not guarantee uninterrupted operation. We reserve the right to perform scheduled maintenance, apply security patches, and modify platform features to ensure ongoing security and stability.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">6. Intellectual Property</h2>
            <p>
              The Application, including its software, design, trademarks, and documentation, is owned by its operators and protected by applicable intellectual property laws. Your hotel operational data remains your property; we claim no ownership over your business records. You are granted a limited, non-exclusive, revocable license to use the Application solely as permitted by these Terms.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">7. Limitation of Liability</h2>
            <p>
              To the maximum extent permitted by law, the Application is provided "as is" without warranties of any kind, express or implied. We shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or for any loss of revenue, profit, data, or business arising out of your use of, or inability to use, the Application, even if advised of the possibility of such damages.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">8. Indemnification</h2>
            <p>
              You agree to indemnify and hold harmless the operators of the Application from any claims, losses, liabilities, and expenses (including reasonable legal fees) arising out of your misuse of the Application, your violation of these Terms, or your infringement of any third-party rights.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">9. Termination</h2>
            <p>
              We may suspend or terminate your access to the Application at any time, with or without notice, for conduct that violates these Terms, applicable law, or the integrity of the platform. Upon termination, your right to use the Application ceases, and we may delete or retain data in accordance with our retention practices.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">10. Governing Law</h2>
            <p>
              These Terms are governed by and construed in accordance with the laws of the jurisdiction in which the operating entity is established, without regard to its conflict-of-laws principles. Any disputes shall be resolved in the courts of competent jurisdiction for that entity.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">11. Changes to These Terms</h2>
            <p>
              We may revise these Terms from time to time. Continued use of the Application after changes become effective constitutes acceptance of the revised Terms. The "Effective Date" above reflects the latest revision.
            </p>
          </section>

          <section>
            <h2 className="text-base font-bold text-gray-900 mb-2">12. Contact &amp; Entire Agreement</h2>
            <p>
              These Terms, together with our Privacy Policy, constitute the entire agreement between you and the operators of the Application regarding its use. For questions about these Terms, contact your designated System Administrator or Property Owner through the in-platform support channels provided to your organization.
            </p>
          </section>
        </div>

        <div className="mt-8 pt-4 border-t border-gray-100 text-xs text-gray-500 flex flex-wrap items-center gap-2">
          <Shield className="h-3.5 w-3.5" />
          <span>Related:</span>
          <Link to="/privacy" className="font-medium text-red-700 hover:text-red-800 hover:underline">
            Privacy Policy
          </Link>
        </div>
      </div>
    </div>
  );
}
