// Auto-generated by Base44 CLI - DO NOT EDIT
// Regenerate with: base44 types generate

export interface AuditLog {
  /**
   * The action performed (e.g., 'User Created', 'delete_account', 'auto_payroll')
   */
  action: string;
  /**
   * User ID the audit entry is about
   */
  user_id?: string;
  /**
   * Username of the user the entry is about
   */
  username?: string;
  /**
   * User ID of the person who performed the action
   */
  performed_by_id?: string;
  /**
   * Username/email of the person who performed the action
   */
  performed_by?: string;
  /**
   * Client IP that performed the action
   */
  ip_address?: string;
  /**
   * Device/fingerprint of the client
   */
  device?: string;
  property_id?: string;
  property_name?: string;
  /**
   * success | failed
   */
  result?: string;
  /**
   * Additional context of the action
   */
  detail?: string;
  /**
   * Hash of this entry for the tamper-evident chain
   */
  hash?: string;
  /**
   * Hash of the previous entry in the chain
   */
  previous_hash?: string;
  created_date?: string;
  updated_date?: string;
}

export interface Channel {
  property_id?: string;
  property_name?: string;
  channel_name: string;
  channel_type?: "ota" | "direct" | "walk_in" | "corporate" | "other";
  commission_type?: "percentage" | "fixed" | "actual" | "none";
  commission_rate?: number;
  commission_amount?: number;
  gross_revenue?: number;
  net_revenue?: number;
  commission_status?: "configured" | "not_configured" | "actual";
  date?: string;
  stays?: number;
}

export interface ClerkShiftRecord {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  record_type: "payment" | "drop" | "clerk_payment";
  payment_type?: string;
  clerk_name?: string;
  shift_date?: string;
  actual?: number;
  adjusted?: number;
  net_today?: number;
  amount?: number;
  transaction_count?: number;
}

export interface Expense {
  property_id?: string;
  property_name?: string;
  expense_name: string;
  vendor?: string;
  category?:
    | "utilities"
    | "payroll"
    | "housekeeping"
    | "maintenance"
    | "insurance"
    | "supplies"
    | "marketing"
    | "ota_commission"
    | "taxes"
    | "rent"
    | "other";
  frequency?: "one_time" | "weekly" | "monthly" | "quarterly" | "yearly";
  amount: number;
  expense_date?: string;
  payment_status?: "unpaid" | "scheduled" | "paid" | "overdue";
  recurring?: boolean;
  taxable?: boolean;
  notes?: string;
}

export interface GrossRevenueDay {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  date: string;
  day_of_week?: string;
  room_rent?: number;
  misc_charge?: number;
  system_charge?: number;
  food?: number;
  event?: number;
  bar?: number;
  laundry?: number;
  phone?: number;
  other?: number;
  non_revenue?: number;
  advance_deposit?: number;
  beverage?: number;
}

export interface OccupancyDay {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  date: string;
  day_of_week?: string;
  room_revenue?: number;
  other_room_revenue?: number;
  total_revenue?: number;
  total_rooms?: number;
  rooms_sold?: number;
  rooms_sold_without_comp?: number;
  down_rooms?: number;
  vacant_rooms?: number;
  clean_rooms?: number;
  dirty_rooms?: number;
  stayover_rooms?: number;
  same_day_bookings?: number;
  comp_rooms?: number;
  house_rooms?: number;
  zero_rate_rooms?: number;
  day_use_rooms?: number;
  no_shows?: number;
  cancellations?: number;
  total_guests?: number;
  adr?: number;
  occupancy?: number;
  revpar?: number;
}

export interface PaymentDay {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  date: string;
  day_of_week?: string;
  cash?: number;
  check?: number;
  closed_balance_folio?: number;
  corpay?: number;
  direct_bill?: number;
  loyalty_certificate?: number;
  loyalty_discount?: number;
  vip_pass?: number;
  wire_transfer?: number;
  amex?: number;
  discover?: number;
  master?: number;
  other?: number;
  visa?: number;
  total?: number;
}

export interface PayrollRun {
  property_id?: string;
  property_name?: string;
  employee_name: string;
  department?: string;
  pay_type?: "hourly" | "salary";
  base_rate?: number;
  hours?: number;
  regular_pay?: number;
  overtime_hours?: number;
  overtime_rate?: number;
  overtime_pay?: number;
  bonus?: number;
  deductions?: number;
  total_pay?: number;
  pay_period_start?: string;
  pay_period_end?: string;
  payroll_status?: "draft" | "pending_review" | "approved" | "paid";
  payroll_date?: string;
}

export interface Property {
  code: string;
  name: string;
  rooms?: number;
  address?: string;
  city?: string;
  state?: string;
  phone?: string;
  active?: boolean;
}

export interface RateLimit {
  /**
   * Client IP the rate bucket applies to
   */
  ip: string;
  /**
   * The action being rate limited (e.g. "login")
   */
  action: string;
  /**
   * Number of attempts recorded in the current window
   */
  count?: number;
  /**
   * ISO date-time when the bucket resets
   */
  reset_at?: string;
  created_date?: string;
  updated_date?: string;
}

export interface Session {
  /**
   * ID of the user this session belongs to
   */
  user_id: string;
  /**
   * SHA-256 hash of the session token
   */
  token_hash: string;
  /**
   * ISO date string when the session expires
   */
  expires_at: string;
  /**
   * IP address of the client (for anomaly detection)
   */
  ip_address?: string;
  /**
   * User-Agent string of the client
   */
  user_agent?: string;
  /**
   * If true, this session has been forcefully revoked
   */
  is_revoked?: boolean;
  created_date?: string;
  updated_date?: string;
}

export interface SourceDay {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  date: string;
  day_of_week?: string;
  code?: string;
  source?: string;
  net_revenue?: number;
  stays?: number;
  adr?: number;
  occupancy_contribution?: number;
  revpar_contribution?: number;
}

export interface Staff {
  property_id?: string;
  property_name?: string;
  employee_id?: string;
  employee_name: string;
  department?: string;
  role_title?: string;
  pay_type?: "hourly" | "salary";
  base_rate?: number;
  hours?: number;
  overtime_hours?: number;
  overtime_rate?: number;
  bonus?: number;
  deductions?: number;
  hire_date?: string;
  active?: boolean;
}

export interface TimecardPunch {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  employee_name: string;
  employee_id?: string;
  department?: string;
  shift_date: string;
  clock_in?: string;
  clock_out?: string;
  break_minutes?: number;
}

export interface UploadedReport {
  property_id?: string;
  property_name?: string;
  report_type?: string;
  import_id?: string;
  source_file?: string;
  drive_file_id?: string;
  drive_backup_status?: string;
  file_name: string;
  rows_imported?: number;
  rows_skipped?: number;
  rows_parsed?: number;
  file_url?: string;
  columns?: string[];
  raw_rows?: {}[];
}

export interface User {
  username: string;
  display_name?: string;
  /**
   * Highest privilege in the app. `owner` (app admin) and `admin` (manager) bypass per-property restrictions; the remaining roles are restricted to `property_access`.
   */
  role?: "owner" | "admin" | "manager" | "front_desk" | "accountant" | "read_only" | "user";
  /**
   * Which properties this user may view or edit. "all" (or null) = unrestricted; an array of property IDs restricts access. Anything else (or an empty array) grants no property access.
   */
  property_access?: string | string[];
  /**
   * Optional per-feature capability flags (e.g. { "import": true, "delete": false })
   */
  permissions?: {};
  /**
   * Disabled users cannot sign in or use sessions.
   */
  is_active?: boolean;
  /**
   * Locked users are forced through the admin unlock flow.
   */
  is_locked?: boolean;
  /**
   * Forced password change on next login (temp passwords).
   */
  must_change_password?: boolean;
  /**
   * Whether a second factor is required at sign-in.
   */
  mfa_enabled?: boolean;
  /**
   * Whether the email address has been verified.
   */
  email_confirmed?: boolean;
  /**
   * SCrypt hash (never the plaintext password).
   */
  password_hash?: string;
  salt?: string;
  /**
   * TOTP secret (base32) used for authenticator apps. Kept server-side only.
   */
  mfa_secret?: string;
  /**
   * Hashed single-use password-reset token.
   */
  reset_token_hash?: string;
  /**
   * ISO date-time when the reset token expires.
   */
  reset_token_expires_at?: string;
  last_login?: string;
  failed_login_count?: number;
  locked_until?: string;
  session_created?: string;
  session_expires?: string;
}

declare module '@base44/sdk' {
  interface EntityTypeRegistry {
    "AuditLog": AuditLog;
    "Channel": Channel;
    "ClerkShiftRecord": ClerkShiftRecord;
    "Expense": Expense;
    "GrossRevenueDay": GrossRevenueDay;
    "OccupancyDay": OccupancyDay;
    "PaymentDay": PaymentDay;
    "PayrollRun": PayrollRun;
    "Property": Property;
    "RateLimit": RateLimit;
    "Session": Session;
    "SourceDay": SourceDay;
    "Staff": Staff;
    "TimecardPunch": TimecardPunch;
    "UploadedReport": UploadedReport;
    "User": User;
  }
  
  interface FunctionNameRegistry {
    "autoPayroll": true;
    "aiAssistant": true;
    "backupToDrive": true;
    "audit_clear": true;
    "audit_list": true;
    "custom_auth_login": true;
    "audit_log": true;
    "custom_auth_register": true;
    "custom_auth_reset_request": true;
    "custom_auth_logout": true;
    "custom_auth_me": true;
    "custom_user_admin": true;
    "custom_auth_reset_password": true;
    "importDriveFile": true;
    "deleteAccount": true;
    "getWeather": true;
    "listDriveFiles": true;
  }
  
  interface ConnectorTypeRegistry {
    "googledrive": true;
  }
}