import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from "react";
import { X, Percent, ToggleLeft, ToggleRight, Save } from "lucide-react";
import { getTaxConfig, setTaxConfig, formatTaxRate } from "@/lib/taxConfig";
export default function TaxConfigModal({ open, onClose }) {
    const [config, setConfig] = useState(getTaxConfig());
    if (!open)
        return null;
    const handleSave = () => {
        setTaxConfig(config);
        onClose();
    };
    const toggleSource = (key) => {
        setConfig({
            ...config,
            sources: config.sources.map((s) => s.key === key ? { ...s, taxable: !s.taxable } : s),
        });
    };
    const ratePercent = (Number(config.taxRate) || 0) * 100;
    return (_jsx("div", { className: "fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4 backdrop-blur-sm", children: _jsxs("div", { className: "w-full max-w-md rounded-2xl border border-white/10 bg-[#151921] p-6 shadow-2xl", children: [_jsxs("div", { className: "mb-5 flex items-center justify-between", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx(Percent, { className: "h-5 w-5 text-[#00D4FF]" }), _jsx("h2", { className: "font-heading text-lg font-semibold text-white", children: "Tax Configuration" })] }), _jsx("button", { onClick: onClose, className: "text-slate-400 hover:text-white", children: _jsx(X, { className: "h-5 w-5" }) })] }), _jsxs("div", { className: "mb-5 flex items-center justify-between rounded-xl border border-white/5 bg-[#0b0e14] px-4 py-3", children: [_jsxs("div", { children: [_jsx("p", { className: "text-sm font-medium text-white", children: "Apply Tax" }), _jsx("p", { className: "text-xs text-slate-500", children: "Enable or disable tax calculation globally" })] }), _jsx("button", { onClick: () => setConfig({ ...config, taxEnabled: !config.taxEnabled }), children: config.taxEnabled ? (_jsx(ToggleRight, { className: "h-7 w-7 text-[#00E096]" })) : (_jsx(ToggleLeft, { className: "h-7 w-7 text-slate-600" })) })] }), _jsxs("div", { className: "mb-5", children: [_jsx("label", { className: "mb-1.5 block text-xs font-medium uppercase tracking-widest text-slate-400", children: "Tax Rate (%)" }), _jsxs("div", { className: "relative", children: [_jsx("input", { type: "number", step: "0.01", value: ratePercent.toFixed(2), onChange: (e) => {
                                        const pct = parseFloat(e.target.value) || 0;
                                        setConfig({ ...config, taxRate: pct / 100 });
                                    }, disabled: !config.taxEnabled, className: "w-full rounded-lg border border-white/10 bg-[#0b0e14] px-4 py-2.5 text-sm text-white outline-none focus:border-[#00D4FF] disabled:opacity-40" }), _jsx("span", { className: "absolute right-3 top-1/2 -translate-y-1/2 text-sm text-slate-500", children: "%" })] }), _jsxs("p", { className: "mt-1 text-xs text-slate-500", children: ["Combined tax rate \u00B7 Currently ", formatTaxRate(config.taxRate)] })] }), _jsxs("div", { className: "mb-5 rounded-xl border border-[#00D4FF]/15 bg-[#00D4FF]/[0.04] p-3", children: [_jsx("p", { className: "text-xs text-slate-400", children: "Formula" }), _jsxs("p", { className: "mt-1 font-mono text-sm text-[#00D4FF]", children: ["Tax = Room Rent \u00D7 ", formatTaxRate(config.taxRate)] }), _jsxs("div", { className: "mt-2 space-y-0.5 text-xs text-slate-500", children: [_jsxs("p", { children: ["$100 \u00D7 ", formatTaxRate(config.taxRate), " = $", (100 * config.taxRate).toFixed(2)] }), _jsxs("p", { children: ["$200 \u00D7 ", formatTaxRate(config.taxRate), " = $", (200 * config.taxRate).toFixed(2)] }), _jsxs("p", { children: ["$300 \u00D7 ", formatTaxRate(config.taxRate), " = $", (300 * config.taxRate).toFixed(2)] })] })] }), _jsxs("div", { className: "mb-5", children: [_jsx("p", { className: "mb-2 text-xs font-medium uppercase tracking-widest text-slate-400", children: "Taxable Booking Sources" }), _jsx("div", { className: "space-y-1.5", children: config.sources.map((src) => (_jsxs("button", { onClick: () => toggleSource(src.key), disabled: !config.taxEnabled, className: "flex w-full items-center justify-between rounded-lg border border-white/5 bg-[#0b0e14] px-4 py-2.5 text-left transition-colors hover:border-white/10 disabled:opacity-40", children: [_jsx("span", { className: "text-sm text-slate-200", children: src.label }), src.taxable ? (_jsxs("span", { className: "flex items-center gap-1 text-xs text-[#00E096]", children: [_jsx(ToggleRight, { className: "h-5 w-5" }), " Taxable"] })) : (_jsxs("span", { className: "flex items-center gap-1 text-xs text-slate-500", children: [_jsx(ToggleLeft, { className: "h-5 w-5" }), " Exempt"] }))] }, src.key))) })] }), _jsxs("div", { className: "flex justify-end gap-3", children: [_jsx("button", { onClick: onClose, className: "rounded-lg border border-white/10 px-4 py-2 text-sm text-slate-300 hover:bg-white/5", children: "Cancel" }), _jsxs("button", { onClick: handleSave, className: "flex items-center gap-1.5 rounded-lg bg-[#6C63FF] px-4 py-2 text-sm font-medium text-white hover:bg-[#5b52e8]", children: [_jsx(Save, { className: "h-4 w-4" }), " Save Tax Config"] })] })] }) }));
}
